version: '3.8'

services:
  # PostgreSQL with PGVector extension for storing embeddings
  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector_db
    environment:
      POSTGRES_USER: sagar
      POSTGRES_PASSWORD: narisetti
      POSTGRES_DB: rag_database
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - rag_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sagar -d rag_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Streamlit application container
  streamlit_app:
    build: .
      # context: .
      # dockerfile: Dockerfile
    container_name: streamlit_app
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app # Mount application code
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://sagar:narisetti@pgvector:5432/rag_database
      - HF_HOME=/app/model                    # HuggingFace home directory
      - TRANSFORMERS_CACHE=/app/model       # HuggingFace cache location
      - HF_HUB_OFFLINE=1
    networks:
      - rag_network

volumes:
  pgvector_data: # Persistent storage for PostgreSQL data
  huggingface_cache:

networks:
  rag_network:
    driver: bridge