---
# ------------------- PostgreSQL + pgvector Deployment -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16 # Use the official pgvector image with PostgreSQL 16
          ports:
            - containerPort: 5432
              name: pgvector-port
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "sagar", "-d", "myvectordb"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "sagar", "-d", "myvectordb"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: init-script
          configMap:
            name: pg-init-schema
            
---
# ------------ RAG App (Streamlit + LLM) Deployment -----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app-deployment
  namespace: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      serviceAccountName: bedrock-sa
      containers:
      - name: rag-app
        image: 185990503656.dkr.ecr.eu-west-1.amazonaws.com/rag-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8501
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DATABASE_URL
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: AWS_REGION
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: AWS_DEFAULT_REGION
          - name: HF_HOME
            value: "app/cache"
          - name: TRANSFORMERS_CACHE
            value: "app/cache"
          - name: HF_HUB_OFFLINE
            value: "0"
          - name: PYTHONUNBUFFERED
            value: "1"
