apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: rag-app
stringData:
  DB_USER: sagar
  DB_PASSWORD: narisetti
  DB_NAME: myvectordb
  DATABASE_URL: postgresql+psycopg://sagar:narisetti@postgres-service:5432/myvectordb